# Generated by Django 2.0.7 on 2018-07-10 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_coefficient', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regId', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('rating', models.IntegerField()),
                ('orderNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCorrect', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelligentOwl.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('questions_count', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelligentOwl.Game')),
            ],
        ),
        migrations.CreateModel(
            name='TourEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('gameparticipant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IntelligentOwl.GameParticipant')),
                ('school', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('grade', models.IntegerField()),
            ],
            bases=('IntelligentOwl.gameparticipant',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('gameparticipant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='IntelligentOwl.GameParticipant')),
                ('league', models.CharField(max_length=255)),
            ],
            bases=('IntelligentOwl.gameparticipant',),
        ),
        migrations.AddField(
            model_name='tourentry',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelligentOwl.GameParticipant'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='tour_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelligentOwl.TourEntry'),
        ),
        migrations.AddField(
            model_name='question',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelligentOwl.Tour'),
        ),
        migrations.AddField(
            model_name='game',
            name='participants',
            field=models.ManyToManyField(to='IntelligentOwl.GameParticipant'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IntelligentOwl.Team'),
        ),
    ]
